CREATE TABLE IF NOT EXISTS `heroku_97591c0989c66a5`.`content` (
  `postnumber` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(25) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `content` VARCHAR(766) NOT NULL,
  `datetime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`postnumber`))
ENGINE = InnoDB
AUTO_INCREMENT = 271
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_general_cs;

CREATE TABLE IF NOT EXISTS `heroku_97591c0989c66a5`.`users` (
  `username` VARCHAR(50) NOT NULL,
  `pword` VARCHAR(100) NOT NULL,
  `firstname` VARCHAR(50) NOT NULL,
  `lastname` VARCHAR(50) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  UNIQUE INDEX `username` (`username` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_general_cs;